//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Data Structures.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DataStructuresTYPE          130
#define IDD_DATADIALOG                  310
#define IDC_EDIT1                       1000
#define IDC_DATAINPUT                   1000
#define ID_PILAS                        32771
#define ID_COLAS                        32772
#define ID_LISTAS                       32773
#define ID_ARBOLES                      32774
#define ID_STACK_SIMPLENONCIRCULARNORMAL 32775
#define ID_SIMPLENONCIRCULARNORMAL_PUSH 32776
#define ID_SIMPLENONCIRCULARNORMAL_POP  32777
#define ID_STACK_SIMPLENONCIRCULARINVERSE 32778
#define ID_STACK_DOUBLECIRCULARNORMAL   32779
#define ID_SIMPLENONCIRCULARINVERSE_PUSH 32780
#define ID_SIMPLENONCIRCULARINVERSE_POP 32781
#define ID_DOUBLECIRCULARNORMAL_PUSH    32782
#define ID_DOUBLECIRCULARNORMAL_POP     32783
#define ID_QUEUE_SIMPLENONCIRCULARNORMAL1VAR 32784
#define ID_QUEUE_SIMPLENONCIRCULARNORMALWITHTOP 32785
#define ID_QUEUE_DOUBLECIRCULARNORMALWITHOUTTOP 32786
#define ID_SIMPLENONCIRCULARNORMALWITHOUTTOP_PUSH 32787
#define ID_SIMPLENONCIRCULARNORMALWITHOUTTOP_POP 32788
#define ID_SIMPLENONCIRCULARNORMALWITHTOP_PUSH 32789
#define ID_SIMPLENONCIRCULARNORMALWITHTOP_POP 32790
#define ID_DOUBLECIRCULARNORMALWITHOUTTOP_PUSH 32791
#define ID_DOUBLECIRCULARNORMALWITHOUTTOP_POP 32792
#define ID_LIST_SIMPLEDESCENDANT        32793
#define ID_SIMPLEDESCENDANT_PUSH        32794
#define ID_SIMPLEDESCENDANT_POP         32795
#define ID_LIST_DOUBLEASCENDANT         32796
#define ID_DOUBLEASCENDANT_PUSH         32797
#define ID_DOUBLEASCENDANT_POP          32798
#define ID_TREE_BINARY                  32799
#define ID_BINARY_PUSH                  32800
#define ID_BINARY_POP                   32801
#define ID_THREADEDTREE_PUSH            32802
#define ID_TREE_THREADED                32803
#define ID_THREADED_PUSH                32804
#define ID_THREADED_POP                 32805

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        311
#define _APS_NEXT_COMMAND_VALUE         32806
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
